### ISSUE TITLE
[swan_core] Cannot find rt.jar when run the program

### ISSUE THREAD

**Issue by feiyangtang97** [secure-software-engineering/swan#32]
Dear creators of SWAN,

I am currently trying to adopt SWAN on my own program to apply some analysis as the idea is very intriguing and the plug-in works very cool! After successfully compiled SWAN_CORE now, I constantly get this error when execute the command to run the jar file:

java -jar target/swan_core-1.4.0-jar-with-dependencies.jar /scanner/target internal internal /scanner/

***** Running with all features.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.RuntimeException: Error: cannot find rt.jar.
        at soot.Scene.defaultJavaClassPath(Scene.java:711)
        at soot.Scene.defaultClassPath(Scene.java:562)
        at soot.Scene.getSootClassPath(Scene.java:299)
        at soot.SourceLocator.getClassSource(SourceLocator.java:168)
        at soot.Scene.tryLoadClass(Scene.java:900)
        at soot.Scene.loadBasicClasses(Scene.java:1652)
        at soot.Scene.loadNecessaryClasses(Scene.java:1738)
        at de.fraunhofer.iem.swan.features.AbstractSootFeature.initializeSoot(AbstractSootFeature.java:37)
        at de.fraunhofer.iem.swan.features.AbstractSootFeature.<init>(AbstractSootFeature.java:24)
        at de.fraunhofer.iem.swan.features.MethodClassModifierFeature.<init>(MethodClassModifierFeature.java:22)
        at de.fraunhofer.iem.swan.FeatureHandler.initializeFeatures(FeatureHandler.java:359)
        at de.fraunhofer.iem.swan.Main.internalRun(Main.java:156)
        at de.fraunhofer.iem.swan.Main.run(Main.java:120)
        at de.fraunhofer.iem.swan.Main.main(Main.java:46)

My java path is correct and rt.jar is clearly listed in the folder... I am using JAVA 8 so rt.jar still exists (%JAVAPATH%/jre/lib)... I would be extremely grateful if I could get a hint of enlightening from you guys on this issue since I did not find much documentation on using SWAN as a CLI tool instead of the GUI plug-in.

Thanks a lot in advance!

**Comment by piskachev** [comment]
It seems the path is still not found by Soot. One would need to debug this. 
Soot is used to load the code of all method so that the features can be extracted from there. 
One possibility is that SWAN does not handle all OS-specific file systems. Which OS do you use?
The class path for Soot is configured here:
https://github.com/secure-software-engineering/swan/blob/master/swan_core/src/main/java/de/fraunhofer/iem/swan/Main.java#L155

The FeatureHandler thats the Soot class path as argument. May be you can check there if the path will contain the correct path to your rt.jar.

**Comment by feiyangtang97** [comment]
> It seems the path is still not found by Soot. One would need to debug this.
> Soot is used to load the code of all methods so that the features can be extracted from there.
> One possibility is that SWAN does not handle all OS-specific file systems. Which OS do you use?
> The class path for Soot is configured here:
> https://github.com/secure-software-engineering/swan/blob/master/swan_core/src/main/java/de/fraunhofer/iem/swan/Main.java#L155
> 
> The FeatureHandler takes the Soot class path as argument. May be you can check there if the path will contain the correct path to your rt.jar.

Hi,

Thanks a lot for your quick reply. Yes I suspect it was the Soot issue since there are people reporting this under Soot repo. 

I am currently using Windows10, according to Soot people, this is a common issue for Java version 9 or later but I am using Java 8 which is supposed to work. Will double check the path you just mentioned :) Thanks again.
